name: Build
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: NuGet Restore
      run: nuget restore .\src\Umbraco.Build.sln

    - name: Build app for release
      run: msbuild .\src\Umbraco.Build\Umbraco.Build.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
 
    - name: NuGet Pack
      run: nuget pack .\build\nuspec\Umbraco.Build.nuspec -Properties Solution=$pwd