name: Deploy to MyGet

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
 
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/feature/automated-deploy      

     - name: Get the tag name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Output version to build
      run: Write-Host Deploying version ${{ env.Version }}

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: NuGet Restore
      run: nuget restore .\src\Umbraco.Build.sln

    - name: Build app for release
      run: msbuild .\src\Umbraco.Build\Umbraco.Build.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
 
    - name: NuGet Pack
      run: nuget pack .\build\nuspec\Umbraco.Build.nuspec -Properties Solution=$pwd /p:Version=${{ env.Version }}

    - name: Push
      run: dotnet nuget push Umbraco.Build.$($env:GITHUB_REF -replace "refs/tags/").nupkg --api-key ${MYGET_API_KEY} --source https://www.myget.org/F/umbracocore/api/v3/index.json
      env:
        MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}