name: Deploy to MyGet

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
 
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: Build the project and output npkg
      run: .\build\build.ps1