name: Deploy to MyGet

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
 
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - name: Get version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/feature/automated-deploy      

    - name: Output version to build
      run: echo "Deploying version $VERSION"

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    
    - name: NuGet Restore
      run: nuget restore .\src\Umbraco.Build.sln

    - name: Build app for release
      run: msbuild .\src\Umbraco.Build\Umbraco.Build.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
 
    - name: NuGet Pack
      run: nuget pack .\build\nuspec\Umbraco.Build.nuspec -Properties Solution=$pwd /p:Version=${VERSION}

